language: python

os: linux
dist: xenial

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -r PythonClient/requirements.txt
  - pip install pylint

script:
  - pylint --errors-only --rcfile=PythonClient/.pylintrc PythonClient/carla PythonClient/*.py
