site_name: CARLA Simulator
repo_url: https://github.com/carla-simulator/carla
docs_dir: Docs

pages:
- Home: 'index.md'
- Using CARLA:
  - 'How to run CARLA server and client': 'how_to_run.md'
  - 'CARLA Settings': 'carla_settings.md'
  - 'Measurements': 'measurements.md'
  - 'Cameras and sensors': 'cameras_and_sensors.md'
  - 'Troubleshooting': 'troubleshooting.md'
- Building from source:
  - 'How to build on Linux': 'how_to_build_on_linux.md'
  - 'How to build on Windows': 'how_to_build_on_windows.md'
  - 'How to add Automotive Materials': 'how_to_add_automotive_materials.md'
- Development:
  - 'Map customization': 'map_customization.md'
  - 'How to add assets': 'how_to_add_assets.md'
  - 'CarlaServer documentation': 'carla_server.md'

markdown_extensions:
  - admonition
